mutation CreateCategory(
  $color: String,
  $hasDescription: Boolean,
  $hasTitle: Boolean,
  $hasUnit: Boolean,
  $icon: String,
  $title: String!,
  $type: String!,
  $unit: String,
) {
  createCategory(
    color: $color,
    hasDescription: $hasDescription,
    hasTitle: $hasTitle,
    hasUnit: $hasUnit,
    icon: $icon,
    title: $title,
    type: $type,
    unit: $unit
    ) {
      color
      hasDescription
      hasTitle
      hasUnit
      icon
      id
      title
      type
      unit
    }
}

mutation UpdateCategory(
  $color: String!,
  $hasDescription: Boolean,
  $hasTitle: Boolean,
  $hasUnit: Boolean,
  $icon: String,
  $id: Int!,
  $title: String!,
  $type: String!,
  $unit: String,
) {
  updateCategory(
    color: $color,
    hasDescription: $hasDescription,
    hasTitle: $hasTitle,
    hasUnit: $hasUnit
    icon: $icon,
    id: $id,
    title: $title,
    type: $type,
    unit: $unit
  ) {
    id
    title
  }
}
