query GetCategories {
  getCategories {
    id
    title
	}
}

query GetCategory($id: Int!) {
  getCategory(id: $id) {
    color
    hasDescription
    hasTitle
    hasUnit
    icon
    id
    title
    type
    unit
	}
}
