query GetCategories {
  getCategories {
    id
    title
    hasSubcategories
  }
}

query GetCategoriesIcon {
  getCategories {
    color
    icon
    id
    type
  }
}

query GetCategory($id: Int!) {
  getCategory(id: $id) {
    color
    hasDescription
    hasSubcategories
    hasTitle
    hasUnit
    icon
    id
    title
    type
    unit
	}
}

query GetCategoryWithChildren($id: Int!) {
  getCategory(id: $id) {
    color
    hasDescription
    hasSubcategories
    hasTitle
    hasUnit
    icon
    id
    title
    type
    unit
    subcategories {
      id
      title
    }
	}
}

query GetCategoryPlainWithChildren($id: Int!) {
  getCategory(id: $id) {
    hasSubcategories
    id
    title
    subcategories {
      id
      title
    }
	}
}
