mutation CreateWidget($title: String!, $type: String!, $value: String) {
  createWidget(value: $value, title: $title, type: $type) {
    id
    title
	}
}

mutation UpdateWidget($id: Int!, $title: String!, $type: String!, $value: String) {
  updateWidget(id: $id, title: $title, type: $type, value: $value) {
    id
    title
    type
    value
	}
}

mutation DeleteWidget($id: Int!) {
  deleteWidget(id: $id)
}
