query GetWidget($id: Int!) {
  getWidget(id: $id) {
    id
    title
    value
    type
    position
	}
}

query GetWidgets {
  getWidgets {
    id
    title
    type
    value
    position
    evaluation {
      id
      title
      categoryId
      groupSubcategories
      type
      period
      category {
        title
      }
      result {
        labels
        datasets {
          label
          data
          backgroundColor
        }
      }
    }
	}
}


query GetWidgetsOverview {
  getWidgets {
    id
    title
    type
    value
    position
	}
}
