mutation CreateRecord(
  $amount: String,
  $categoryId: Int!,
  $description: String,
  $title: String
  ) {
  createRecord(
    amount: $amount,
    categoryId: $categoryId,
    description: $description,
    title: $title
    ) {
      id
      title
      amount
      description
      createdAt
      category {
        id
        icon
        color
        type
        hasUnit
        unit
      }
    }
}
