mutation CreateRecord(
  $amount: String,
  $categoryId: Int!,
  $description: String,
  $title: String
  ) {
  createRecord(
    amount: $amount,
    categoryId: $categoryId,
    description: $description,
    title: $title
    ) {
      id
    }
}
