mutation LoginUser($username: String!, $password: String!, $device: String!) {
  loginUser(username: $username, password: $password, device: $device) {
    id
    token
    role
    userSettings {
      value
      setting {
        type
      }
    }
    userSession {
      id
      token
      expiresAt
      createdAt
    }
  }
}

mutation DeleteUserSession($id: Int!) {
  deleteUserSession(id: $id)
}