mutation LoginUser($username: String!, $password: String!) {
  loginUser(username: $username, password: $password) {
    id
    token
    role
    userSettings {
      value
      setting {
        type
      }
    }
  }
}
